# Generated by Django 4.1.6 on 2023-02-18 15:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('effort', models.CharField(choices=[('Myself', 'Myself'), ('Other', 'Other'), ('Task', 'Task')], default='Myself', max_length=150)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
