# Generated by Django 4.1.6 on 2023-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('effort', models.CharField(choices=[('myself', 'myself'), ('other', 'other'), ('pratice', 'pratice')], default=True, max_length=150)),
            ],
        ),
    ]
