# Generated by Django 4.1.6 on 2023-02-13 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Task_name', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('effort', models.CharField(choices=[('Myself', 'Myself'), ('Other', 'Other'), ('Task', 'Task')], default='Myself', max_length=150)),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
