# Generated by Django 4.1.6 on 2023-02-15 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='effort',
            field=models.CharField(choices=[('Myself', 'Myself'), ('Other', 'Other'), ('Task', 'Task')], default='Myself', max_length=150),
        ),
    ]
