# Generated by Django 4.1.6 on 2023-02-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='effort',
            field=models.CharField(choices=[('myself', 'myself'), ('other', 'other'), ('pratice', 'pratice')], default='myself', max_length=150),
        ),
    ]
