# Generated by Django 4.1.6 on 2023-02-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
