# Generated by Django 4.1.6 on 2023-02-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_task_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='effort',
            field=models.CharField(choices=[('myself', 'myself'), ('other', 'other'), ('pratice', 'pratice')], max_length=150),
        ),
    ]
