# Generated by Django 4.1.6 on 2023-02-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_task_effort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='effort',
        ),
    ]
