# Generated by Django 4.1.6 on 2023-02-11 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_task_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='effort',
            field=models.CharField(choices=[('Myself', 'Myself'), ('Other', 'Other'), ('Task', 'Task')], default=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 3, 58, 42, 997963, tzinfo=datetime.timezone.utc)),
        ),
    ]
