# Generated by Django 4.1.6 on 2023-02-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
