# Generated by Django 4.1.6 on 2023-02-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_time_signupform_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupForm',
        ),
    ]
